### ISSUE TITLE
TravisCI: html5validator and rflint fail to install on prod branch

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#1020]
```
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting ansible==2.1.1.0
  Downloading https://files.pythonhosted.org/packages/26/7c/4c717d39afac30bc324744a35fda077c969d3881daf71d396969958e01b7/ansible-2.1.1.0.tar.gz (1.9MB)
Collecting paramiko (from ansible==2.1.1.0)
  Downloading https://files.pythonhosted.org/packages/cf/ae/94e70d49044ccc234bfdba20114fa947d7ba6eb68a2e452d89b920e62227/paramiko-2.4.2-py2.py3-none-any.whl (193kB)
Collecting jinja2 (from ansible==2.1.1.0)
  Downloading https://files.pythonhosted.org/packages/1d/e7/fd8b501e7a6dfe492a433deb7b9d833d39ca74916fa8bc63dd1a4947a671/Jinja2-2.10.1-py2.py3-none-any.whl (124kB)
Requirement already satisfied: PyYAML in /usr/lib/python2.7/dist-packages (from ansible==2.1.1.0) (3.11)
Requirement already satisfied: setuptools in /usr/local/lib/python2.7/dist-packages (from ansible==2.1.1.0) (40.8.0)
Collecting pycrypto>=2.6 (from ansible==2.1.1.0)
  Downloading https://files.pythonhosted.org/packages/60/db/645aa9af249f059cc3a368b118de33889219e0362141e75d4eaf6f80f163/pycrypto-2.6.1.tar.gz (446kB)
Requirement already satisfied: pyasn1>=0.1.7 in /usr/lib/python2.7/dist-packages (from paramiko->ansible==2.1.1.0) (0.1.9)
Collecting bcrypt>=3.1.3 (from paramiko->ansible==2.1.1.0)
  Downloading https://files.pythonhosted.org/packages/50/d8/95f7cb04344033bf9d1a12c5a7969a15999b6a710fbe1969c517333d9a62/bcrypt-3.1.6-cp27-cp27mu-manylinux1_x86_64.whl (59kB)
Collecting cryptography>=1.5 (from paramiko->ansible==2.1.1.0)
  Downloading https://files.pythonhosted.org/packages/c3/c1/cf8665c955c9393e9ff0872ba6cd3dc6f46ef915e94afcf6e0410508ca69/cryptography-2.6.1-cp27-cp27mu-manylinux1_x86_64.whl (2.3MB)
Collecting pynacl>=1.0.1 (from paramiko->ansible==2.1.1.0)
  Downloading https://files.pythonhosted.org/packages/b3/25/e605574f24948a8a53b497744e93f061eb1dbe7c44b6465fc1c172d591aa/PyNaCl-1.3.0-cp27-cp27mu-manylinux1_x86_64.whl (762kB)
Collecting MarkupSafe>=0.23 (from jinja2->ansible==2.1.1.0)
  Downloading https://files.pythonhosted.org/packages/fb/40/f3adb7cf24a8012813c5edb20329eb22d5d8e2a0ecf73d21d6b85865da11/MarkupSafe-1.1.1-cp27-cp27mu-manylinux1_x86_64.whl
Requirement already satisfied: six>=1.4.1 in /usr/lib/python2.7/dist-packages (from bcrypt>=3.1.3->paramiko->ansible==2.1.1.0) (1.10.0)
Collecting cffi>=1.1 (from bcrypt>=3.1.3->paramiko->ansible==2.1.1.0)
  Downloading https://files.pythonhosted.org/packages/8d/e9/0c8afd1579e5cf7bc0f06fbcd7cdb954cbc0baadd505973949a99337da1c/cffi-1.12.3-cp27-cp27mu-manylinux1_x86_64.whl (415kB)
Requirement already satisfied: enum34; python_version < "3" in /usr/lib/python2.7/dist-packages (from cryptography>=1.5->paramiko->ansible==2.1.1.0) (1.1.2)
Collecting asn1crypto>=0.21.0 (from cryptography>=1.5->paramiko->ansible==2.1.1.0)
  Downloading https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl (101kB)
Requirement already satisfied: ipaddress; python_version < "3" in /usr/lib/python2.7/dist-packages (from cryptography>=1.5->paramiko->ansible==2.1.1.0) (1.0.16)
Collecting pycparser (from cffi>=1.1->bcrypt>=3.1.3->paramiko->ansible==2.1.1.0)
  Downloading https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz (158kB)
Building wheels for collected packages: ansible, pycrypto, pycparser
  Building wheel for ansible (setup.py): started
  Building wheel for ansible (setup.py): finished with status 'done'
  Stored in directory: /home/travis/.cache/pip/wheels/31/d9/d0/79e339e96062f5042d2d30b6cbf6a567e27213bed4f96b3f38
  Building wheel for pycrypto (setup.py): started
  Building wheel for pycrypto (setup.py): finished with status 'done'
  Stored in directory: /home/travis/.cache/pip/wheels/27/02/5e/77a69d0c16bb63c6ed32f5386f33a2809c94bd5414a2f6c196
  Building wheel for pycparser (setup.py): started
  Building wheel for pycparser (setup.py): finished with status 'done'
  Stored in directory: /home/travis/.cache/pip/wheels/f2/9a/90/de94f8556265ddc9d9c8b271b0f63e57b26fb1d67a45564511
Successfully built ansible pycrypto pycparser
Installing collected packages: pycparser, cffi, bcrypt, asn1crypto, cryptography, pynacl, paramiko, MarkupSafe, jinja2, pycrypto, ansible
Successfully installed MarkupSafe-1.1.1 ansible-2.1.1.0 asn1crypto-0.24.0 bcrypt-3.1.6 cffi-1.12.3 cryptography-2.6.1 jinja2-2.10.1 paramiko-2.4.2 pycparser-2.19 pycrypto-2.6.1 pynacl-1.3.0
You are using pip version 19.0.3, however version 19.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
/home/travis/.nvm/versions/node/v8.12.0/bin/bootlint -> /home/travis/.nvm/versions/node/v8.12.0/lib/node_modules/bootlint/src/cli-main.js
+ bootlint@0.16.6
added 119 packages from 53 contributors in 4.604s
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 6, in <module>
    from pip._internal import main
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cli/main_parser.py", line 12, in <module>
    from pip._internal.commands import (
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/commands/__init__.py", line 6, in <module>
    from pip._internal.commands.completion import CompletionCommand
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/commands/completion.py", line 6, in <module>
    from pip._internal.cli.base_command import Command
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cli/base_command.py", line 20, in <module>
    from pip._internal.download import PipSession
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/download.py", line 15, in <module>
    from pip._vendor import requests, six, urllib3
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/__init__.py", line 97, in <module>
    from pip._vendor.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 6, in <module>
    from pip._internal import main
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cli/main_parser.py", line 12, in <module>
    from pip._internal.commands import (
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/commands/__init__.py", line 6, in <module>
    from pip._internal.commands.completion import CompletionCommand
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/commands/completion.py", line 6, in <module>
    from pip._internal.cli.base_command import Command
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cli/base_command.py", line 20, in <module>
    from pip._internal.download import PipSession
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/download.py", line 15, in <module>
    from pip._vendor import requests, six, urllib3
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/__init__.py", line 97, in <module>
    from pip._vendor.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  shellcheck
0 upgraded, 1 newly installed, 0 to remove and 72 not upgraded.
Need to get 1,603 kB of archives.
After this operation, 13.3 MB of additional disk space will be used.
Get:1 http://us-east-1.ec2.archive.ubuntu.com/ubuntu xenial/universe amd64 shellcheck amd64 0.3.7-5 [1,603 kB]
Fetched 1,603 kB in 0s (6,291 kB/s)
Selecting previously unselected package shellcheck.
(Reading database ... 124189 files and directories currently installed.)
Preparing to unpack .../shellcheck_0.3.7-5_amd64.deb ...
Unpacking shellcheck (0.3.7-5) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up shellcheck (0.3.7-5) ...
...
=====> Run robot framework lint

./src/main/scripts/ci/check-build-and-verify.sh: line 145: rflint: command not found

=====> Run html5validator

./src/main/scripts/ci/check-build-and-verify.sh: line 182: html5validator: command not found
```
Seen there: https://travis-ci.org/php-coder/mystamps/jobs/528207870

**Comment by php-coder** [comment]
It seems like the issue is related to `pip`.

**Comment by php-coder** [comment]
But why it didn't fail in the beginning?

**Comment by php-coder** [comment]
The bug happens only on `prod` branch. Compare https://travis-ci.org/php-coder/mystamps/jobs/528566524 (master) and https://travis-ci.org/php-coder/mystamps/jobs/528566870 (prod).

The current theory is that the order of installed dependencies is causing the failure. For the prod branch we install ansible first. Perhaps, it brings some dependencies that later affect html5validator/rflint installation.

**Comment by php-coder** [comment]
>  For the prod branch we install ansible first. Perhaps, it brings some dependencies that later affect html5validator/rflint installation.

I was able to reproduce it and play a little. Installing ansible after html5validator/rflint works (see https://travis-ci.org/php-coder/mystamps/builds/529206889).

**Comment by php-coder** [comment]
BTW using the latest (non-pinned) version of Ansible also works.
