### ISSUE TITLE
Ansible fails to stop monitoring: 'NoneType' object has no attribute 'read'

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#1089]
>TASK [Stopping monitoring] *****************************************************
fatal: [my-stamps.ru]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_08uSCH/ansible_module_uptimerobot.py\", line 168, in <module>\r\n    main()\r\n  File \"/tmp/ansible_08uSCH/ansible_module_uptimerobot.py\", line 146, in main\r\n    check_result = checkID(module, params)\r\n  File \"/tmp/ansible_08uSCH/ansible_module_uptimerobot.py\", line 97, in checkID\r\n    result = req.read()\r\nAttributeError: 'NoneType' object has no attribute 'read'\r\n", "msg": "MODULE FAILURE", "parsed": false}

Seen there: https://travis-ci.org/php-coder/mystamps/jobs/561482192

At this moment, deploy to production is blocked by this error.

**Comment by php-coder** [comment]
Here is a workaround: resest `UPTIMEROBOT_APIKEY` env variable, so this part will be skipped.

**Comment by php-coder** [comment]
There is a theory that it could be related to version change of `requests` library.

**Comment by php-coder** [comment]
Might be solved after Ansible update (#1142)

**Comment by php-coder** [comment]
It didn't fail now: https://travis-ci.org/php-coder/mystamps/jobs/619864609

I'll try more times and if it doesn't break, I'll assume that the issue is fixed.

**Comment by php-coder** [comment]
SUCCESS: https://travis-ci.org/php-coder/mystamps/jobs/620294892

**Comment by php-coder** [comment]
It have never fallen since the first Ansible update so I'm closing it.

**Comment by php-coder** [comment]
It has happened again: https://travis-ci.org/php-coder/mystamps/jobs/641141457:
```
TASK [Stopping monitoring] *****************************************************

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'read'

[DEPRECATION WARNING]: Distribution Ubuntu 16.04 on host my-stamps.ru should 

use /usr/bin/python3, but is using /usr/bin/python for backward compatibility 

with prior Ansible releases. A future Ansible release will default to using the

 discovered platform python for this host. See https://docs.ansible.com/ansible

/2.9/reference_appendices/interpreter_discovery.html for more information. This

 feature will be removed in version 2.12. Deprecation warnings can be disabled 

by setting deprecation_warnings=False in ansible.cfg.

fatal: [my-stamps.ru]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "module_stderr": "Shared connection to my-stamps.ru closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/data/mystamps/.ansible/tmp/ansible-tmp-1579858278.32-251061803888530/AnsiballZ_uptimerobot.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/data/mystamps/.ansible/tmp/ansible-tmp-1579858278.32-251061803888530/AnsiballZ_uptimerobot.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/data/mystamps/.ansible/tmp/ansible-tmp-1579858278.32-251061803888530/AnsiballZ_uptimerobot.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible.modules.monitoring.uptimerobot', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib/python2.7/runpy.py\", line 188, in run_module\r\n    fname, loader, pkg_name)\r\n  File \"/usr/lib/python2.7/runpy.py\", line 82, in _run_module_code\r\n    mod_name, mod_fname, mod_loader, pkg_name)\r\n  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code\r\n    exec code in run_globals\r\n  File \"/tmp/ansible_uptimerobot_payload_wdF6O6/ansible_uptimerobot_payload.zip/ansible/modules/monitoring/uptimerobot.py\", line 151, in <module>\r\n  File \"/tmp/ansible_uptimerobot_payload_wdF6O6/ansible_uptimerobot_payload.zip/ansible/modules/monitoring/uptimerobot.py\", line 131, in main\r\n  File \"/tmp/ansible_uptimerobot_payload_wdF6O6/ansible_uptimerobot_payload.zip/ansible/modules/monitoring/uptimerobot.py\", line 82, in checkID\r\nAttributeError: 'NoneType' object has no attribute 'read'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

**Comment by php-coder** [comment]
Perhaps it the same as https://github.com/ansible/ansible/issues/66242

**Comment by php-coder** [comment]
It still there by the way: https://app.travis-ci.com/github/php-coder/mystamps/jobs/556629443

**Comment by php-coder** [comment]
After commit b4e5123baec059527cf8ea024c7dec71395fc464, the failure is more readable now (https://app.travis-ci.com/github/php-coder/mystamps/jobs/582050337):
```
TASK [Stopping monitoring] *****************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'read'
fatal: [my-stamps.ru]: FAILED! => {
    "changed": false,
    "rc": 1
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDOUT:

Traceback (most recent call last):
  File "/data/mystamps/.ansible/tmp/ansible-tmp-1662526163.8195474-187952116238811/AnsiballZ_uptimerobot.py", line 102, in <module>
    _ansiballz_main()
  File "/data/mystamps/.ansible/tmp/ansible-tmp-1662526163.8195474-187952116238811/AnsiballZ_uptimerobot.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/data/mystamps/.ansible/tmp/ansible-tmp-1662526163.8195474-187952116238811/AnsiballZ_uptimerobot.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.monitoring.uptimerobot', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python2.7/runpy.py", line 188, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_uptimerobot_payload_VNjiwb/ansible_uptimerobot_payload.zip/ansible/modules/monitoring/uptimerobot.py", line 151, in <module>
  File "/tmp/ansible_uptimerobot_payload_VNjiwb/ansible_uptimerobot_payload.zip/ansible/modules/monitoring/uptimerobot.py", line 131, in main
  File "/tmp/ansible_uptimerobot_payload_VNjiwb/ansible_uptimerobot_payload.zip/ansible/modules/monitoring/uptimerobot.py", line 82, in checkID
AttributeError: 'NoneType' object has no attribute 'read'
```
