### ISSUE TITLE
JdbcCategoryDaoTest fails on Travis with FileNotFoundException

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#1153]
Regression after 7de05914b856a4e5b08f9b4a16e356924b77818d (#1143)

Unfortunately, due to a bug in Travis the logs haven't been shown (perhaps, because our builds are running a way long without output).

I was able to make them appear in the build https://travis-ci.org/php-coder/mystamps/builds/609765305:

```
460[INFO] Running ru.mystamps.web.feature.category.JdbcCategoryDaoTest
4612019-11-09 21:34:09.008 ERROR   --- [           main] o.s.test.context.TestContextManager      : Caught exception while allowing TestExecutionListener [org.springframework.boot.test.autoconfigure.SpringBootDependencyInjectionTestExecutionListener@5bf61e67] to prepare test instance [ru.mystamps.web.feature.category.JdbcCategoryDaoTest@2c1dc8e]
462
463java.lang.IllegalStateException: Failed to load ApplicationContext
464	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
465	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:83)
466	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:117)
467	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
468	at org.springframework.boot.test.autoconfigure.SpringBootDependencyInjectionTestExecutionListener.prepareTestInstance(SpringBootDependencyInjectionTestExecutionListener.java:43)
469	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:230)
470	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:228)
471	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:287)
472	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
473	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:289)
474	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:247)
475	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
476	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
477	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
478	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
479	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
480	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
481	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
482	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
483	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
484	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
485	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
486	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
487	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
488	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
489	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
490	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
491	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
518	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
519Caused by: java.lang.IllegalStateException: Failed to add PropertySource to Environment
520	at org.springframework.test.context.support.TestPropertySourceUtils.addPropertiesFilesToEnvironment(TestPropertySourceUtils.java:198)
521	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:103)
522	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:98)
523	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:116)
524	... 28 common frames omitted
525Caused by: java.io.FileNotFoundException: class path resource [sql/category_dao_queries.properties] cannot be opened because it does not exist
526	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:172)
527	at org.springframework.core.io.support.EncodedResource.getInputStream(EncodedResource.java:154)
528	at org.springframework.core.io.support.PropertiesLoaderUtils.fillProperties(PropertiesLoaderUtils.java:98)
529	at org.springframework.core.io.support.PropertiesLoaderUtils.fillProperties(PropertiesLoaderUtils.java:72)
530	at org.springframework.core.io.support.PropertiesLoaderUtils.loadProperties(PropertiesLoaderUtils.java:58)
531	at org.springframework.core.io.support.ResourcePropertySource.<init>(ResourcePropertySource.java:84)
532	at org.springframework.test.context.support.TestPropertySourceUtils.addPropertiesFilesToEnvironment(TestPropertySourceUtils.java:194)
504	... 31 common frames omitted
```
For unclear yet reasons it didn't fail locally.

**Comment by php-coder** [comment]
> For unclear yet reasons it didn't fail locally.

The reason is that locally I run tests with the command `./mvnw test` while on CI we pass additional parameters to skip some plugins that we don't need.

I was able to reproduce it locally with the command `./mvnw test -Dmaven.resources.skip=true`

Tests fail because `JdbcCategoryDaoTest` requires one of the properties file.
