### ISSUE TITLE
Series import: IllegalArgumentException when only price with currency were extracted

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#1218]
Series import fails when only price/currency were extracted.

Log:
> 2020-01-15 22:30:34.676 [user:1 ]  INFO 61320 --- [qtp307894016-20] r.m.w.f.s.i.SeriesImportServiceImpl      : Request # 1: page were parsed (AddSeriesParsedDataDbDto(...), SeriesSalesParsedDataDbDto(sellerId=null, sellerGroupId=null, sellerName=null, sellerUrl=null, price=660.00, currency=RUB))

Exception:
```
...
Caused by: java.lang.IllegalArgumentException: Seller id must be non null
	at org.apache.commons.lang3.Validate.isTrue(Validate.java:158) ~[commons-lang3-3.8.jar:3.8]
	at ru.mystamps.web.feature.series.sale.SeriesSalesServiceImpl.add(SeriesSalesServiceImpl.java:40) ~[classes/:na]
...
```

**Comment by php-coder** [comment]
It seems like this happens because 1) seller-related fields weren't shown while they should (#1232) and 2) we don't have validation here that prevents this on controller-level (#859)

**Comment by php-coder** [comment]
After fixing #1232 it's hard or nearly impossible to reproduce this issue: the fields for name/url are shown on the page and after form submission they have empty values. Because of that, a participant is created (yes, with empty name, url) and hence sellerId isn't null now.

But after fixing #851 and #854 it should become reproducible again.

**Comment by php-coder** [comment]
> But after fixing #851 and #854 it should become reproducible again.

The exception is different this time:

```
Caused by: java.lang.IllegalArgumentException: Name must be non null
	at org.apache.commons.lang3.Validate.isTrue(Validate.java:158) ~[commons-lang3-3.8.jar:3.8]
	at ru.mystamps.web.feature.participant.ParticipantServiceImpl.add(ParticipantServiceImpl.java:42) ~[classes/:na]
```
