### ISSUE TITLE
rflint fails with ImportError: No module named txtreader

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#1404]
```
=====> Run robot framework lint

Traceback (most recent call last):
  File "/home/travis/.local/bin/rflint", line 5, in <module>
    from rflint.__main__ import main
  File "/home/travis/.local/lib/python2.7/site-packages/rflint/__init__.py", line 1, in <module>
    from .rflint import RfLint, ERROR, WARNING
  File "/home/travis/.local/lib/python2.7/site-packages/rflint/rflint.py", line 30, in <module>
    from .parser import RobotFactory, SuiteFile, ResourceFile
  File "/home/travis/.local/lib/python2.7/site-packages/rflint/parser/__init__.py", line 1, in <module>
    from .parser import (SuiteFolder, ResourceFile, SuiteFile, RobotFactory, 
  File "/home/travis/.local/lib/python2.7/site-packages/rflint/parser/parser.py", line 24, in <module>
    from robot.parsing.txtreader import TxtReader
ImportError: No module named txtreader
```
See there: https://travis-ci.org/github/php-coder/mystamps/jobs/690186467

**Comment by php-coder** [comment]
Upstream issue: https://github.com/boakley/robotframework-lint/issues/73

**Comment by php-coder** [comment]
It seems like rflint 1.1 was released recently: https://pypi.org/project/robotframework-lint/1.1/
