### ISSUE TITLE
Update ansible-lint to 4.3.7

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#1516]
Changelogs:
- [x] https://github.com/ansible/ansible-lint/releases/tag/v4.3.0
- [x] https://github.com/ansible/ansible-lint/releases/tag/v4.3.1
- [x] https://github.com/ansible/ansible-lint/releases/tag/v4.3.2
- [x] https://github.com/ansible/ansible-lint/releases/tag/v4.3.3
- [x] https://github.com/ansible/ansible-lint/releases/tag/v4.3.4
- [x] https://github.com/ansible/ansible-lint/releases/tag/v4.3.5
- [x] https://github.com/ansible/ansible-lint/releases/tag/v4.3.6
- [x] https://github.com/ansible/ansible-lint/releases/tag/v4.3.7

**Comment by php-coder** [comment]
It fails locally and on CI (https://github.com/php-coder/mystamps/actions/runs/6649432485/job/18067966405) with the following error:
```
Traceback (most recent call last):
(https://github.com/php-coder/mystamps/actions/runs/6649432485/job/18067966405#step:4:6)
  File "/home/runner/.local/bin/ansible-lint", line 5, in <module>
(https://github.com/php-coder/mystamps/actions/runs/6649432485/job/18067966405#step:4:7)
    from ansiblelint.__main__ import main
(https://github.com/php-coder/mystamps/actions/runs/6649432485/job/18067966405#step:4:8)
  File "/home/runner/.local/lib/python3.8/site-packages/ansiblelint/__main__.py", line 37, in <module>
(https://github.com/php-coder/mystamps/actions/runs/6649432485/job/18067966405#step:4:9)
    from ansiblelint.generate_docs import rules_as_rich, rules_as_rst
(https://github.com/php-coder/mystamps/actions/runs/6649432485/job/18067966405#step:4:10)
  File "/home/runner/.local/lib/python3.8/site-packages/ansiblelint/generate_docs.py", line 6, in <module>
(https://github.com/php-coder/mystamps/actions/runs/6649432485/job/18067966405#step:4:11)
    from rich.console import render_group
(https://github.com/php-coder/mystamps/actions/runs/6649432485/job/18067966405#step:4:12)
ImportError: cannot import name 'render_group' from 'rich.console' (/home/runner/.local/lib/python3.8/site-packages/rich/console.py)
(https://github.com/php-coder/mystamps/actions/runs/6649432485/job/18067966405#step:4:13)
Error: Process completed with exit code 1.
```

**Comment by php-coder** [comment]
Here is a related bug: https://github.com/ansible/ansible-lint/issues/1795

**Comment by php-coder** [comment]
Now ansible-lint fails with:
```
Error: [E106] Role name mystamps-app does not match ``^[a-z][a-z0-9_]+$`` pattern
Error: [E106] Role name mystamps-backup does not match ``^[a-z][a-z0-9_]+$`` pattern
Error: [E106] Role name mystamps-nginx does not match ``^[a-z][a-z0-9_]+$`` pattern
Error: [E106] Role name mystamps-user does not match ``^[a-z][a-z0-9_]+$`` pattern
```
See https://github.com/php-coder/mystamps/actions/runs/6674854345/job/18142194426
