### ISSUE TITLE
countryShouldBeAvailableForChoosingAtPageWithSeries: fix StaleElementReference

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#280]
Our integration tests fail sporadically with the following error (example: https://travis-ci.org/php-coder/mystamps/builds/87893389):

```
countryShouldBeAvailableForChoosingAtPageWithSeries(ru.mystamps.web.tests.cases.WhenAdminAddCountry)  Time elapsed: 0.481 sec  <<< FAILURE!
org.openqa.selenium.StaleElementReferenceException: The element seems to be disconnected from the DOM.  This means that a user cannot interact with it.
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.47.1', revision: 'unknown', time: '2015-07-30 11:02:44'
System info: host: 'MacBook-Pro-rock.local', ip: '192.168.0.2', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.8.0_45'
Driver info: driver.version: HtmlUnitDriver
    at org.openqa.selenium.htmlunit.HtmlUnitDriver.assertElementNotStale(HtmlUnitDriver.java:809)
    at org.openqa.selenium.htmlunit.HtmlUnitWebElement.assertElementNotStale(HtmlUnitWebElement.java:860)
    at org.openqa.selenium.htmlunit.HtmlUnitWebElement.getText(HtmlUnitWebElement.java:518)
    at ru.mystamps.web.tests.page.AddSeriesPage$$Lambda$1/625981223.apply(Unknown Source)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at ru.mystamps.web.tests.page.AddSeriesPage.getCountryFieldValues(AddSeriesPage.java:126)
    at ru.mystamps.web.tests.cases.WhenAdminAddCountry.countryShouldBeAvailableForChoosingAtPageWithSeries(WhenAdminAddCountry.java:242)


Results :

Failed tests:
  WhenAdminAddCountry>AbstractTestNGSpringContextTests.run:175->countryShouldBeAvailableForChoosingAtPageWithSeries:242 » StaleElementReference

Tests run: 303, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by php-coder** [comment]
After porting this test to Robot Framework we have a different error and perhaps a bit different problem that will be addressed by #540
