### ISSUE TITLE
Problem with adding big image

### ISSUE THREAD

**Issue by cssru** [php-coder/mystamps#303]
On series creation trying to add .pgm image file (size 13,5 Mb) - we get "500 Internal server error".
Exception:
java.lang.IllegalStateException: Multipart Mime part image exceeds max filesize

**Comment by php-coder** [comment]
It's better to provide the stacktrace to simplify debug and for the history:

```
[2016-01-07 00:31:10.602] boot - 62051  WARN [qtp1947856995-19] --- ServletHandler: /series/add
java.lang.IllegalStateException: Request exceeds maxRequestSize (3145728)
	at org.eclipse.jetty.util.MultiPartInputStreamParser.parse(MultiPartInputStreamParser.java:642)
	at org.eclipse.jetty.util.MultiPartInputStreamParser.getParts(MultiPartInputStreamParser.java:400)
	at org.eclipse.jetty.server.Request.getParts(Request.java:2139)
	at org.eclipse.jetty.server.Request.extractMultipartParameters(Request.java:385)
	at org.eclipse.jetty.server.Request.extractContentParameters(Request.java:308)
	at org.eclipse.jetty.server.Request.extractParameters(Request.java:256)
	at org.eclipse.jetty.server.Request.getParameter(Request.java:825)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:70)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.servlets.gzip.GzipHandler.handle(GzipHandler.java:299)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by php-coder** [comment]
This limit set to the 10Mb in `application.properties`: `multipart.max-request-size: 10Mb`.

**Comment by php-coder** [comment]
We should handle this exception and return 413 Request Entity Too Large status code instead of 500.

**Comment by cssru** [comment]
If we should - we will!
I suppose we need @ExceptionHandler in SeriesController and additional error page in views/error for 413 code.

**Comment by php-coder** [comment]
You could try it for yourself, but I think that it wouldn't work because exception happens in filter before getting any controllers.

**Comment by cssru** [comment]
You are right.
Then we can extend Hidden­HttpMethodFilter and handle exception.

**Comment by php-coder** [comment]
I'm thinking about using `MultipatFilter` here. Probably it could help.

**Comment by php-coder** [comment]
Also we have a bit different exception when trying to upload 6Mb file:

```
java.lang.IllegalStateException: Multipart Mime part image exceeds max filesize
	at org.eclipse.jetty.util.MultiPartInputStreamParser$MultiPart.write(MultiPartInputStreamParser.java:111)
	at org.eclipse.jetty.util.MultiPartInputStreamParser.parse(MultiPartInputStreamParser.java:681)
	at org.eclipse.jetty.util.MultiPartInputStreamParser.getParts(MultiPartInputStreamParser.java:400)
	at org.eclipse.jetty.server.Request.getParts(Request.java:2139)
	at org.eclipse.jetty.server.Request.extractMultipartParameters(Request.java:385)
	at org.eclipse.jetty.server.Request.extractContentParameters(Request.java:308)
	at org.eclipse.jetty.server.Request.extractParameters(Request.java:256)
	at org.eclipse.jetty.server.Request.getParameter(Request.java:825)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:70)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.servlets.gzip.GzipHandler.handle(GzipHandler.java:299)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
```
Because in this case we exceed another limit: `multipart.max-file-size: 5Mb`

**Comment by cssru** [comment]
И опять-таки здесь замешан org.springframewo­rk.web.filter.HiddenHttpMethodFilter, от которого, по ходу все идет :-) Может, все-таки его extend?

**Comment by cssru** [comment]
Have you seen this?
http://stackoverflow.com/questions/29363705/handling-multipartexception-with-spring-boot-and-display-error-page

**Comment by cssru** [comment]
Or:
public class CustomHiddenHttpMethodFilter extends HiddenHttpMethodFilter {
    protected void doFilterInternal(HttpServletRequest request,
                                HttpServletResponse response,
                                FilterChain filterChain)
                         throws ServletException, IOException {
          try {
               super.doFilterInternal(request, response, filterChain);
          } catch (IllegalStateException ise) {
              throw new MultipartException();
              // or: response.sendError(HttpServletResponse.SC_REQUEST_ENTITY_TOO_LARGE);
          }
    }
}
