### ISSUE TITLE
Build scripts: check database upgrade before deploy

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#383]

**Comment by php-coder** [comment]
After updating password in `src/main/resources/liquibase/liquibase.properties`, creating SSH tunnel (`ssh -L 3306:localhost:3306 my-stamps.ru`) and run `mvn liquibase:status` I got the following error:
```
59 change sets have not been applied to mystamps@localhost@jdbc:mysql://localhost:3306/mystamps
     /Users/coder/git/mystamps.git/src/main/resources/liquibase/initial-state.xml::create-users_activation-table::php-coder
     /Users/coder/git/mystamps.git/src/main/resources/liquibase/initial-state.xml::create-users_table::php-coder
...
It turns out that the path to the migration is also very important. When we run migration during application startup we have prefix `classpath:/` (example: `classpath:/liquibase/version/0.4/2016-02-19--csrf_events.xml`). When I run it locally it has prefix `` (example: `/Users/coder/git/mystamps.git/src/main/resources/`). Looks like we should unify `changeLogFile` parameter in `liquibase-maven-plugin` with `liquibase.change-log` from `application-prod.properties`.

**Comment by php-coder** [comment]
We should only modify `changeLogFile` parameter in `liquibase-maven-plugin` because `classpath:` prefix will be ignored (since 3.0.6 version). See for details: http://stackoverflow.com/questions/16605099/using-liquibase-file-paths-via-both-maven-and-spring

**Comment by php-coder** [comment]
Command for checking for updates should be `mvn liquibase:status -Dliquibase.password=xxx`

**Comment by php-coder** [comment]
Related (ssh tunnel & ansible): https://stackoverflow.com/questions/31264121/ansible-and-liquibase-integration

**Comment by php-coder** [comment]
Here is how to disable starting of Web server: https://www.baeldung.com/spring-boot-no-web-server

**Comment by php-coder** [comment]
This regression might not occur: #1557

**Comment by php-coder** [comment]
The output of Ansible playbook when everything is fine:
```

PLAY [all] *********************************************************************************************************************************************************************************************************************************

TASK [Getting info about WAR file] *********************************************************************************************************************************************************************************************************
ok: [my-stamps.ru -> 127.0.0.1]

TASK [Ensuring that WAR file exists] *******************************************************************************************************************************************************************************************************
ok: [my-stamps.ru -> 127.0.0.1]

TASK [Ensuring whether Liquibase migrations are valid] *************************************************************************************************************************************************************************************
ok: [my-stamps.ru]

TASK [Show stdout of liquibase validate] ***************************************************************************************************************************************************************************************************
ok: [my-stamps.ru] => {
    "liquibase_validate.stdout_lines": [
        "2022-09-05 07:27:22.180 [user:  ]  INFO 27674 --- [           main] r.m.w.s.s.boot.ApplicationBootstrap      : Starting ApplicationBootstrap v0.4.7-SNAPSHOT on my-stamps.ru with PID 27674 (/data/mystamps/mystamps-candidate.war started by mystamps in /data/mystamps)",
        "2022-09-05 07:27:22.200 [user:  ] DEBUG 27674 --- [           main] r.m.w.s.s.boot.ApplicationBootstrap      : Running with Spring Boot v2.1.18.RELEASE, Spring v5.1.20.RELEASE",
        "2022-09-05 07:27:22.201 [user:  ]  INFO 27674 --- [           main] r.m.w.s.s.boot.ApplicationBootstrap      : The following profiles are active: test",
        "2022-09-05 07:27:24.268 [user:  ]  INFO 27674 --- [           main] liquibase.integration                    : Liquibase did not run because System property 'liquibase.shouldRun' was set to false",
        "2022-09-05 07:27:24.336 [user:  ]  INFO 27674 --- [           main] r.m.w.s.s.boot.ApplicationBootstrap      : Started ApplicationBootstrap in 3.814 seconds (JVM running for 4.867)",
        "2022-09-05 07:27:24.339 [user:  ]  INFO 27674 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...",
        "2022-09-05 07:27:24.909 [user:  ]  INFO 27674 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.",
        "2022-09-05 07:27:25.106 [user:  ]  INFO 27674 --- [           main] liquibase.database                       : Set default schema name to PUBLIC",
        "2022-09-05 07:27:25.127 [user:  ]  INFO 27674 --- [           main] r.m.w.s.liquibase.LiquibaseSupport       : Validating the migrations",
        "2022-09-05 07:27:25.141 [user:  ]  INFO 27674 --- [           main] liquibase.servicelocator                 : Cannot load service: liquibase.parser.ChangeLogParser: Provider liquibase.parser.core.json.JsonChangeLogParser could not be instantiated",
        "2022-09-05 07:27:25.154 [user:  ]  INFO 27674 --- [           main] liquibase.servicelocator                 : Cannot load service: liquibase.parser.ChangeLogParser: Provider liquibase.parser.core.yaml.YamlChangeLogParser could not be instantiated",
        "2022-09-05 07:27:29.901 [user:  ]  INFO 27674 --- [           main] r.m.w.s.liquibase.LiquibaseSupport       : Migrations are valid",
        "2022-09-05 07:27:29.905 [user:  ]  INFO 27674 --- [       Thread-1] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...",
        "2022-09-05 07:27:29.914 [user:  ]  INFO 27674 --- [       Thread-1] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.",
        "0"
    ]
}

TASK [Show stderr of liquibase validate] ***************************************************************************************************************************************************************************************************
ok: [my-stamps.ru] => {
    "liquibase_validate.stderr_lines": []
}
```

**Comment by php-coder** [comment]
The output of Ansible playbook when one of migration is invalid:
```
TASK [Ensuring whether Liquibase migrations are valid] *************************************************************************************************************************************************************************************
fatal: [my-stamps.ru]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "cmd": "set -eu\neval \"$(sed -n '/^[A-Z]/s||export &|p' mystamps.conf)\"\njava $JAVA_OPTS -jar mystamps-candidate.war liquibase validate\n",
    "delta": "0:00:10.400534",
    "end": "2022-09-06 06:06:29.660387",
    "rc": 1,
    "start": "2022-09-06 06:06:19.259853"
}

STDOUT:

2022-09-06 06:06:22.237 [user:  ]  INFO 3325 --- [           main] r.m.w.s.s.boot.ApplicationBootstrap      : Starting ApplicationBootstrap v0.4.7-SNAPSHOT on my-stamps.ru with PID 3325 (/data/mystamps/mystamps-candidate.war started by mystamps in /data/mystamps)
2022-09-06 06:06:22.255 [user:  ] DEBUG 3325 --- [           main] r.m.w.s.s.boot.ApplicationBootstrap      : Running with Spring Boot v2.1.18.RELEASE, Spring v5.1.20.RELEASE
2022-09-06 06:06:22.256 [user:  ]  INFO 3325 --- [           main] r.m.w.s.s.boot.ApplicationBootstrap      : The following profiles are active: prod
2022-09-06 06:06:24.483 [user:  ]  INFO 3325 --- [           main] liquibase.integration                    : Liquibase did not run because System property 'liquibase.shouldRun' was set to false
2022-09-06 06:06:24.543 [user:  ]  INFO 3325 --- [           main] r.m.w.s.s.boot.ApplicationBootstrap      : Started ApplicationBootstrap in 4.205 seconds (JVM running for 5.276)
2022-09-06 06:06:24.546 [user:  ]  INFO 3325 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2022-09-06 06:06:25.137 [user:  ]  INFO 3325 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2022-09-06 06:06:25.347 [user:  ]  INFO 3325 --- [           main] r.m.w.s.liquibase.LiquibaseSupport       : Validating the migrations
2022-09-06 06:06:25.389 [user:  ]  INFO 3325 --- [           main] liquibase.servicelocator                 : Cannot load service: liquibase.parser.ChangeLogParser: Provider liquibase.parser.core.json.JsonChangeLogParser could not be instantiated
2022-09-06 06:06:25.411 [user:  ]  INFO 3325 --- [           main] liquibase.servicelocator                 : Cannot load service: liquibase.parser.ChangeLogParser: Provider liquibase.parser.core.yaml.YamlChangeLogParser could not be instantiated
2022-09-06 06:06:29.000 [user:  ]  INFO 3325 --- [           main] liquibase.changelog                      : Reading from mystamps.DATABASECHANGELOG
2022-09-06 06:06:29.614 [user:  ] ERROR 3325 --- [           main] r.m.w.s.liquibase.LiquibaseSupport       : Failed to validate migrations

liquibase.exception.ValidationFailedException: Validation Failed:
     2 change sets check sum
          liquibase/version/0.4.4/2020-05-23--modify_condition_field.xml::modify-collections_series-condition-field::php-coder was: 8:04ed13bc0d22dbc6d8b228421c46cabe but is now: 8:e68d35a7c2773ef7e4f064a6b365a115
          liquibase/version/0.4.4/2020-05-23--modify_condition_field.xml::modify-series_sales-condition-field::php-coder was: 8:293900b116eb46f9f4134cca74d50056 but is now: 8:26084de457d9fbc7274e8828a9a9ecfc

	at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:296) ~[liquibase-core-4.11.0.jar!/:na]
	at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:272) ~[liquibase-core-4.11.0.jar!/:na]
	at ru.mystamps.web.support.liquibase.LiquibaseSupport.validate(LiquibaseSupport.java:113) [classes!/:0.4.7-SNAPSHOT]
	at ru.mystamps.web.support.liquibase.LiquibaseSupport.performLiquibaseValidate(LiquibaseSupport.java:96) [classes!/:0.4.7-SNAPSHOT]
	at ru.mystamps.web.support.liquibase.LiquibaseSupport.validate(LiquibaseSupport.java:78) [classes!/:0.4.7-SNAPSHOT]
	at ru.mystamps.web.support.spring.boot.ApplicationBootstrap.main(ApplicationBootstrap.java:52) [classes!/:0.4.7-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [mystamps-candidate.war:0.4.7-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [mystamps-candidate.war:0.4.7-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [mystamps-candidate.war:0.4.7-SNAPSHOT]
	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:58) [mystamps-candidate.war:0.4.7-SNAPSHOT]

2022-09-06 06:06:29.628 [user:  ]  INFO 3325 --- [       Thread-1] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2022-09-06 06:06:29.638 [user:  ]  INFO 3325 --- [       Thread-1] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.


STDERR:

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:58)
Caused by: liquibase.exception.ValidationFailedException: Validation Failed:
     2 change sets check sum
          liquibase/version/0.4.4/2020-05-23--modify_condition_field.xml::modify-collections_series-condition-field::php-coder was: 8:04ed13bc0d22dbc6d8b228421c46cabe but is now: 8:e68d35a7c2773ef7e4f064a6b365a115
          liquibase/version/0.4.4/2020-05-23--modify_condition_field.xml::modify-series_sales-condition-field::php-coder was: 8:293900b116eb46f9f4134cca74d50056 but is now: 8:26084de457d9fbc7274e8828a9a9ecfc

	at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:296)
	at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:272)
	at ru.mystamps.web.support.liquibase.LiquibaseSupport.validate(LiquibaseSupport.java:113)
	at ru.mystamps.web.support.liquibase.LiquibaseSupport.performLiquibaseValidate(LiquibaseSupport.java:96)
	at ru.mystamps.web.support.liquibase.LiquibaseSupport.validate(LiquibaseSupport.java:78)
	at ru.mystamps.web.support.spring.boot.ApplicationBootstrap.main(ApplicationBootstrap.java:52)
	... 8 more


MSG:

non-zero return code
```

**Comment by php-coder** [comment]
Fails in TravisCI as expected (because of #1557): https://app.travis-ci.com/github/php-coder/mystamps/jobs/581907556
