### ISSUE TITLE
/collection/{slug}: EmptyResultDataAccessException with not existing id

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#449]
When I open not existing collection `/collection/10/foo` I should get 404 error, but currently I see 500:

```
Aug 18 23:56:04 my-stamps.ru java[21650]: Caused by: org.springframework.dao.EmptyResultDataAccessException: Incorrect result size: expected 1, actual 0
Aug 18 23:56:04 my-stamps.ru java[21650]:         at org.springframework.dao.support.DataAccessUtils.requiredSingleResult(DataAccessUtils.java:71)
Aug 18 23:56:04 my-stamps.ru java[21650]:         at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.queryForObject(NamedParameterJdbcTemplate.java:212)
Aug 18 23:56:04 my-stamps.ru java[21650]:         at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.queryForObject(NamedParameterJdbcTemplate.java:219)
Aug 18 23:56:04 my-stamps.ru java[21650]:         at ru.mystamps.web.dao.impl.JdbcCollectionDao.findCollectionInfoById(JdbcCollectionDao.java:176)
Aug 18 23:56:04 my-stamps.ru java[21650]:         at ru.mystamps.web.service.CollectionServiceImpl.findById(CollectionServiceImpl.java:153)
Aug 18 23:56:04 my-stamps.ru java[21650]:         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Aug 18 23:56:04 my-stamps.ru java[21650]:         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Aug 18 23:56:04 my-stamps.ru java[21650]:         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Aug 18 23:56:04 my-stamps.ru java[21650]:         at java.lang.reflect.Method.invoke(Method.java:498)
Aug 18 23:56:04 my-stamps.ru java[21650]:         at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
Aug 18 23:56:04 my-stamps.ru java[21650]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
Aug 18 23:56:04 my-stamps.ru java[21650]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
Aug 18 23:56:04 my-stamps.ru java[21650]:         at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
Aug 18 23:56:04 my-stamps.ru java[21650]:         at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
Aug 18 23:56:04 my-stamps.ru java[21650]:         at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
Aug 18 23:56:04 my-stamps.ru java[21650]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
Aug 18 23:56:04 my-stamps.ru java[21650]:         at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
Aug 18 23:56:04 my-stamps.ru java[21650]:         at com.sun.proxy.$Proxy57.findById(Unknown Source)
Aug 18 23:56:04 my-stamps.ru java[21650]:         at ru.mystamps.web.controller.CollectionController.showInfo(CollectionController.java:66)
```

**Comment by php-coder** [comment]
In addition to the fix I would like to have an integration test for that case.

Hints:
- we can use [`WhenAnonymousUserOpenNotExistingCategoryPage` test](https://github.com/php-coder/mystamps/blob/b2f1c612d9eba7a957edc602c3431de848fd55e1/src/test/java/ru/mystamps/web/tests/cases/WhenAnonymousUserOpenNotExistingCategoryPage.java) as example
- we have to add `InfoCollectionPage` (and use [InfoSeriesPage](https://github.com/php-coder/mystamps/blob/b2f1c612d9eba7a957edc602c3431de848fd55e1/src/test/java/ru/mystamps/web/tests/page/InfoSeriesPage.java) as example)

**Comment by php-coder** [comment]
@bodom91 This will be your next task.

**Comment by bodom91** [comment]
My Solution https://github.com/bodom91/mystamps/commit/d2f0d9bdf55876dc77804ce855cff66b7a7c04e8

But im not sure about `InfoCollectionPage` and now i dont have idea, sorry ...((

**Comment by php-coder** [comment]
> But im not sure about InfoCollectionPage and now i dont have idea, sorry ...((

Ah, I see now that we don't need it. I'm sorry, I've updated the description.
